steps:
- name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git clone https://github.com/TSRINEVAS/tf_gke/
      cd tf_gke
      terraform init
      terraform apply -auto-approve
    
      options:
  logging: CLOUD_LOGGING_ONLY
