steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--depth=1', 'https://github.com/your/repo.git']
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    dir: 'repo/path/to/terraform/config'
  - name: 'hashicorp/terraform:latest'
    args: ['apply', '-auto-approve']
    dir: 'repo/path/to/terraform/config'
